spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  flyway:
    url: jdbc:mariadb://localhost:3306/expenses?useSSL=false
    user: root
    password: root
